@extends('layouts.site')

@section('title', 'Privacy Policy - iPassGenerator')
@section('description', 'Review our privacy policy to understand how we collect, use, and protect your personal information when using the iPassGenerator password generator tool.')

@section('schema')
@php
echo '<script type="application/ld+json">';
echo '{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "name": "iPassGenerator",
      "url": "https://ipassgenerator.com",
      "description": "Free online secure password generator tool for creating strong, random passwords with customizable options.",
      "publisher": {
        "@type": "Organization",
        "name": "iPassGenerator",
        "url": "https://ipassgenerator.com",
        "logo": "https://ipassgenerator.com/favicon.svg"
      }
    },
    {
      "@type": "WebPage",
      "name": "Privacy Policy - iPassGenerator",
      "url": "https://ipassgenerator.com/privacy",
      "description": "Review our privacy policy to understand how we collect, use, and protect your personal information when using the iPassGenerator password generator tool.",
      "isPartOf": {
        "@type": "WebSite",
        "name": "iPassGenerator",
        "url": "https://ipassgenerator.com"
      },
      "datePublished": "2026-04-27",
      "dateModified": "2026-04-27"
    },
    {
      "@type": "Organization",
      "name": "iPassGenerator",
      "url": "https://ipassgenerator.com",
      "logo": "https://ipassgenerator.com/favicon.svg",
      "description": "Provider of free online password generation tools focused on security and privacy."
    }
  ]
}';
echo '</script>';
@endphp
@endsection

@section('content')
  <section class="mx-auto w-full max-w-4xl rounded-3xl border border-studio-line bg-studio-card p-6 shadow-panel dark:border-slate-700 dark:bg-slate-800 sm:p-8">
    <h1 class="text-3xl font-semibold tracking-tight">Privacy Policy</h1>
    <div class="mt-6 space-y-5 text-[1.02rem] leading-7 text-studio-muted dark:text-slate-300">
      <p>This website is provided for informational and utility purposes. While we aim to offer a reliable password generation tool, the site is provided on an “as is” basis without warranties of uninterrupted availability or fitness for a particular purpose.</p>
      <p>You are responsible for how you use any password generated by this site, including where you store it and whether you use additional protective measures such as a password manager and multi-factor authentication.</p>
      <p>You agree not to misuse the website, attempt to interfere with its operation, or use automated methods to abuse the service, generate invalid ad traffic, or disrupt the experience for other visitors.</p>
      <p>We may update these terms from time to time as the site evolves. Continued use of the website after updates are published constitutes acceptance of the revised terms.</p>
    </div>
  </section>
@endsection
